version: "3.8"

services:
  app:
    build: .
    ports:
      - "6970:6970"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=https://staging-adgen.sigmagrowthpartners.com
    volumes:
      - app_data:/data
    networks:
      - shared_n8n

networks:
  shared_n8n:
    external: true

volumes:
  app_data:
