version: "3.8"

services:
  app:
    build: .
    ports:
      - "6970:6970"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=https://staging-adgen.sigmagrowthpartners.com
    volumes:
      - .:/usr/src/app
      - app_data:/data
      - /usr/src/app/node_modules
    networks:
      - shared_n8n
    command: sh -c "npm install && npm run dev"


networks:
  shared_n8n:
    external: true

volumes:
  app_data:
